services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 512mb

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/taskdb
      SECRET_KEY: your-super-secret-key-change-in-production
      ENVIRONMENT: production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 &&
             alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 1"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

volumes:
  postgres_data: 