services:
  db:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
      POSTGRES_HOST: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  backend:
    build: 
      context: ./backend1
      dockerfile: Dockerfile
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend1/src:/app/src
      - ./backend1/alembic.ini:/app/alembic.ini
      - ./backend1/migrations:/app/migrations
      - ./backend1/.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - REDIS_URL=redis://redis:6379/0
    working_dir: /app/src
    networks:
      - mynetwork

  celery:
    image: backend1
    platform: linux/amd64
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ./backend1/src:/app/src
      - ./backend1/.env:/app/.env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - REDIS_URL=redis://redis:6379/0
    working_dir: /app/src
    networks:
      - mynetwork

  celery-beat:
    image: backend1
    platform: linux/amd64
    command: celery -A celery_app.celery_app beat --loglevel=info
    volumes:
      - ./backend1/src:/app/src
      - ./backend1/.env:/app/.env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - REDIS_URL=redis://redis:6379/0
    working_dir: /app/src
    networks:
      - mynetwork
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
