services:
  db:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
      POSTGRES_HOST: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/src:/app/src
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/migrations:/app/migrations
      - ./backend/.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/postgresdb
    working_dir: /app/src
    networks:
      - mynetwork
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
